<html style="" lang="en" class="js flexbox fontface"><head><meta charset="utf-8"><meta content="width=device-width, initial-scale=1.0" name="viewport"><title>Error Handling - Real World OCaml</title><link href="css/app.css" rel="stylesheet"><link href="css/prism.css" rel="stylesheet"><script src="js/min/modernizr-min.js"></script><script src="js/prism.js"></script><script src="//use.typekit.net/gfj8wez.js"></script><script>try{Typekit.load();}catch(e){}</script></head><body><div class="title-bar"><div class="title"><h1>Real World OCaml</h1><h5>2<sup>nd</sup> Edition (in progress)</h5><nav><a href="index.html">Home</a><a href="toc.html">Table of Contents</a><a href="faqs.html">FAQs</a><a href="install.html">Install</a><a href="https://ocaml.janestreet.com/ocaml-core/">API Docs</a></nav></div></div><div class="wrap"><div class="left-column"><a class="to-chapter" href="toc.html"><small>Back</small><h5>Table of Contents</h5></a></div><article class="main-body"><section class="level1" id="error-handling">
<h1>Error Handling</h1>
<p>Nobody likes dealing with errors. It’s tedious, it’s easy to get wrong, and it’s usually just not as fun as thinking about how your program is going to succeed. But error handling is important, and however much you don’t like thinking about it, having your software fail due to poor error handling is worse.</p>
<p>Thankfully, OCaml has powerful tools for handling errors reliably and with a minimum of pain. In this chapter we’ll discuss some of the different approaches in OCaml to handling errors, and give some advice on how to design interfaces that make error handling easier.</p>
<p>We’ll start by describing the two basic approaches for reporting errors in OCaml: error-aware return types and exceptions. <a id="erraware" data-primary="error-aware return types" data-type="indexterm">&nbsp;</a><a id="EHeraware" data-secondary="error-aware return types" data-primary="error handling" data-type="indexterm">&nbsp;</a></p>
<section class="level2" id="error-aware-return-types">
<h2>Error-Aware Return Types</h2>
<p>The best way in OCaml to signal an error is to include that error in your return value. Consider the type of the <code>find</code> function in the <code>List</code> module:</p>
<div class="highlight">
<pre data-filter-output=">" data-prompt="#" class="command-line"><code class="language-ocaml">open Base;;
List.find;;
&gt;- : 'a list -&gt; f:('a -&gt; bool) -&gt; 'a option = &lt;fun&gt;
</code></pre>
</div>
<p>The option in the return type indicates that the function may not succeed in finding a suitable element:</p>
<div class="highlight">
<pre data-filter-output=">" data-prompt="#" class="command-line"><code class="language-ocaml">List.find [1;2;3] ~f:(fun x -&gt; x &gt;= 2);;
&gt;- : int option = Some 2
List.find [1;2;3] ~f:(fun x -&gt; x &gt;= 10);;
&gt;- : int option = None
</code></pre>
</div>
<p>Including errors in the return values of your functions requires the caller to handle the error explicitly, allowing the caller to make the choice of whether to recover from the error or propagate it onward.</p>
<p>Consider the <code>compute_bounds</code> function below, which takes a list and a comparison function and returns upper and lower bounds for the list by finding the smallest and largest element on the list. <code>List.hd</code> and <code>List.last</code>, which return <code>None</code> when they encounter an empty list, are used to extract the largest and smallest element of the list:</p>
<div class="highlight">
<pre data-filter-output=">" data-prompt="#" class="command-line"><code class="language-ocaml">let compute_bounds ~compare list =
  let sorted = List.sort ~compare list in
  match List.hd sorted, List.last sorted with
  | None,_ | _, None -&gt; None
  | Some x, Some y -&gt; Some (x,y)
;;
&gt;val compute_bounds : compare:('a -&gt; 'a -&gt; int) -&gt; 'a list -&gt; ('a * 'a) option =
&gt;  &lt;fun&gt;
</code></pre>
</div>
<p>The <code>match</code> statement is used to handle the error cases, propagating a <code>None</code> in <code>hd</code> or <code>last</code> into the return value of <code>compute_bounds</code>.</p>
<p>On the other hand, in the <code>find_mismatches</code> that follows, errors encountered during the computation do not propagate to the return value of the function. <code>find_mismatches</code> takes two hash tables as arguments and searches for keys that have different data in one table than in the other. As such, the failure to find a key in one table isn’t a failure of any sort:</p>
<div class="highlight">
<pre data-filter-output=">" data-prompt="#" class="command-line"><code class="language-ocaml">let find_mismatches table1 table2 =
  Hashtbl.fold table1 ~init:[] ~f:(fun ~key ~data mismatches -&gt;
    match Hashtbl.find table2 key with
    | Some data' when data' &lt;&gt; data -&gt; key :: mismatches
    | _ -&gt; mismatches
  )
;;
&gt;val find_mismatches :
&gt;  ('a, int) Hashtbl.Poly.t -&gt; ('a, int) Hashtbl.Poly.t -&gt; 'a list = &lt;fun&gt;
</code></pre>
</div>
<p>The use of options to encode errors underlines the fact that it’s not clear whether a particular outcome, like not finding something on a list, is an error or is just another valid outcome. This depends on the larger context of your program, and thus is not something that a general-purpose library can know in advance. One of the advantages of error-aware return types is that they work well in both situations.</p>
<section class="level3" id="encoding-errors-with-result">
<h3>Encoding Errors with Result</h3>
<p>Options aren’t always a sufficiently expressive way to report errors. Specifically, when you encode an error as <code>None</code>, there’s nowhere to say anything about the nature of the error.</p>
<p><code>Result.t</code> is meant to address this deficiency. The type is defined as follows:<a data-primary="Result.t option" data-type="indexterm">&nbsp;</a></p>
<div class="highlight">
<pre><code class="language-ocaml">module Result : sig
   type ('a,'b) t = | Ok of 'a
                    | Error of 'b
end</code></pre>
</div>
<p>A <code>Result.t</code> is essentially an option augmented with the ability to store other information in the error case. Like <code>Some</code> and <code>None</code> for options, the constructors <code>Ok</code> and <code>Error</code> are available at the toplevel. As such, we can write:</p>
<div class="highlight">
<pre data-filter-output=">" data-prompt="#" class="command-line"><code class="language-ocaml">[ Ok 3; Error "abject failure"; Ok 4 ];;
&gt;- : (int, string) result list = [Ok 3; Error "abject failure"; Ok 4]
</code></pre>
</div>
<p>without first opening the <code>Result</code> module.</p>
</section>
<section class="level3" id="error-and-or_error">
<h3>Error and Or_error</h3>
<p><code>Result.t</code> gives you complete freedom to choose the type of value you use to represent errors, but it’s often useful to standardize on an error type. Among other things, this makes it easier to write utility functions to automate common error handling patterns.<a data-primary="Error.t type" data-type="indexterm">&nbsp;</a></p>
<p>But which type to choose? Is it better to represent errors as strings? Some more structured representation like XML? Or something else entirely?</p>
<p>Base’s answer to this question is the <code>Error.t</code> type, which tries to forge a good compromise between efficiency, convenience, and control over the presentation of errors.</p>
<p>It might not be obvious at first why efficiency is an issue at all. But generating error messages is an expensive business. An ASCII representation of a value can be quite time-consuming to construct, particularly if it includes expensive-to-convert numerical data.</p>
<p><code>Error</code> gets around this issue through laziness. In particular, an <code>Error.t</code> allows you to put off generation of the error string until and unless you need it, which means a lot of the time you never have to construct it at all. You can of course construct an error directly from a string:</p>
<div class="highlight">
<pre data-filter-output=">" data-prompt="#" class="command-line"><code class="language-ocaml">Error.of_string "something went wrong";;
&gt;- : Error.t = something went wrong
</code></pre>
</div>
<p>But you can also construct an <code>Error.t</code> from a <em>thunk</em>, i.e., a function that takes a single argument of type <code>unit</code>:<a data-primary="thunks" data-type="indexterm">&nbsp;</a></p>
<div class="highlight">
<pre data-filter-output=">" data-prompt="#" class="command-line"><code class="language-ocaml">Error.of_thunk (fun () -&gt;
Printf.sprintf "something went wrong: %f" 32.3343)
;;
&gt;- : Error.t = something went wrong: 32.334300
</code></pre>
</div>
<p>In this case, we can benefit from the laziness of <code>Error</code>, since the thunk won’t be called unless the <code>Error.t</code> is converted to a string.</p>
<p>The most common way to create <code>Error.t</code>s is using <em>s-expressions</em>. An s-expression is a balanced parenthetical expression where the leaves of the expressions are strings. Here’s a simple example: <a data-secondary="example of" data-primary="s-expressions" data-type="indexterm">&nbsp;</a></p>
<div class="highlight">
<pre><code class="language-clike">(This (is an) (s expression))</code></pre>
</div>
<p>S-expressions are supported by the Sexplib package that is distributed with Base and is the most common serialization format used in Base. Indeed, most types in Base come with built-in s-expression converters. <a data-secondary="sexp converter" data-primary="Sexplib package" data-type="indexterm">&nbsp;</a></p>
<div class="highlight">
<pre data-filter-output=">" data-prompt="#" class="command-line"><code class="language-ocaml">Error.create "Unexpected character" 'z' Char.sexp_of_t;;
&gt;- : Error.t = ("Unexpected character" z)
</code></pre>
</div>
<p>Note that the character isn’t actually serialized into an s-expression until the error is printed out.</p>
<p>We’re not restricted to doing this kind of error reporting with built-in types. This will be discussed in more detail in <a data-type="xref" href="data-serialization.html#data-serialization-with-s-expressions">Chapter 19, Data Serialization With S Expressions</a>, but Sexplib comes with a language extension that can autogenerate sexp converters for newly generated types. We can enable it explicitly in the toplevel with a <code>#require</code> statement.</p>


<div class="highlight">
<pre data-filter-output=">" data-prompt="#" class="command-line"><code class="language-ocaml">#require "ppx_jane";;
let custom_to_sexp = [%sexp_of: float * string list * int];;
&gt;val custom_to_sexp : float * string list * int -&gt; Sexp.t = &lt;fun&gt;
custom_to_sexp (3.5, ["a";"b";"c"], 6034);;
&gt;- : Sexp.t = (3.5 (a b c) 6034)
</code></pre>
</div>
<p>We can use this same idiom for generating an error:</p>
<div class="highlight">
<pre data-filter-output=">" data-prompt="#" class="command-line"><code class="language-ocaml">Error.create "Something went terribly wrong"
  (3.5, ["a";"b";"c"], 6034)
  [%sexp_of: float * string list * int]
;;
&gt;- : Error.t = ("Something went terribly wrong" (3.5 (a b c) 6034))
</code></pre>
</div>
<p><code>Error</code> also supports operations for transforming errors. For example, it’s often useful to augment an error with information about the context of the error or to combine multiple errors together. <code>Error.tag</code> and <code>Error.of_list</code> fulfill these roles:<a data-primary="Error.of_list" data-type="indexterm">&nbsp;</a><a data-primary="Error.tag" data-type="indexterm">&nbsp;</a><a data-secondary="transformation of" data-primary="errors" data-type="indexterm">&nbsp;</a></p>
<div class="highlight">
<pre data-filter-output=">" data-prompt="#" class="command-line"><code class="language-ocaml">Error.tag
  (Error.of_list [ Error.of_string "Your tires were slashed";
                   Error.of_string "Your windshield was smashed" ])
  "over the weekend"
;;
&gt;- : Error.t =
&gt;("over the weekend" "Your tires were slashed" "Your windshield was smashed")
</code></pre>
</div>
<p>The type <code>'a Or_error.t</code> is just a shorthand for <code>('a,Error.t) Result.t</code>, and it is, after <code>option</code>, the most common way of returning errors in Base.</p>
</section>
<section class="level3" id="bind-and-other-error-handling-idioms">
<h3><code>bind</code> and Other Error Handling Idioms</h3>
<p>As you write more error handling code in OCaml, you’ll discover that certain patterns start to emerge. A number of these common patterns have been codified by functions in modules like <code>Option</code> and <code>Result</code>. One particularly useful pattern is built around the function <code>bind</code>, which is both an ordinary function and an infix operator <code>&gt;&gt;=</code>. Here’s the definition of <code>bind</code> for options: <a data-primary="bind function" data-type="indexterm">&nbsp;</a></p>
<div class="highlight">
<pre data-filter-output=">" data-prompt="#" class="command-line"><code class="language-ocaml">let bind option f =
  match option with
  | None -&gt; None
  | Some x -&gt; f x
;;
&gt;val bind : 'a option -&gt; ('a -&gt; 'b option) -&gt; 'b option = &lt;fun&gt;
</code></pre>
</div>
<p>As you can see, <code>bind None f</code> returns <code>None</code> without calling <code>f</code>, and <code>bind (Some x) f</code> returns <code>f x</code>. <code>bind</code> can be used as a way of sequencing together error-producing functions so that the first one to produce an error terminates the computation. Here’s a rewrite of <code>compute_bounds</code> to use a nested series of <code>bind</code>s:</p>
<div class="highlight">
<pre data-filter-output=">" data-prompt="#" class="command-line"><code class="language-ocaml">let compute_bounds ~compare list =
  let sorted = List.sort ~compare list in
  Option.bind (List.hd sorted) (fun first -&gt;
    Option.bind (List.last sorted) (fun last -&gt;
      Some (first,last)))
;;
&gt;val compute_bounds : compare:('a -&gt; 'a -&gt; int) -&gt; 'a list -&gt; ('a * 'a) option =
&gt;  &lt;fun&gt;
</code></pre>
</div>
<p>The preceding code is a little bit hard to swallow, however, on a syntactic level. We can make it easier to read and drop some of the parentheses, by using the infix operator form of <code>bind</code>, which we get access to by locally opening <code>Option.Monad_infix</code>. The module is called <code>Monad_infix</code> because the <code>bind</code> operator is part of a subinterface called <code>Monad</code>, which we’ll see again in <a data-type="xref" href="concurrent-programming.html#concurrent-programming-with-async">Chapter 14, Concurrent Programming With Async</a>.</p>
<div class="highlight">
<pre data-filter-output=">" data-prompt="#" class="command-line"><code class="language-ocaml">let compute_bounds ~compare list =
  let open Option.Monad_infix in
  let sorted = List.sort ~compare list in
  List.hd sorted   &gt;&gt;= fun first -&gt;
  List.last sorted &gt;&gt;= fun last  -&gt;
  Some (first,last)
;;
&gt;val compute_bounds : compare:('a -&gt; 'a -&gt; int) -&gt; 'a list -&gt; ('a * 'a) option =
&gt;  &lt;fun&gt;
</code></pre>
</div>
<p>This use of <code>bind</code> isn’t really materially better than the one we started with, and indeed, for small examples like this, direct matching of options is generally better than using <code>bind</code>. But for large, complex examples with many stages of error handling, the <code>bind</code> idiom becomes clearer and easier to manage.</p>
<section data-type="note" class="level5" id="monads-and-let_syntax">
<h5>Monads and <code>Let_syntax</code></h5>
<p>We can make this look a little bit more ordinary by using a syntax extension that’s designed specifically for monadic binds, called <code>Let_syntax</code>. Here’s what the above example looks like using this extension.</p>
<div class="highlight">
<pre data-filter-output=">" data-prompt="#" class="command-line"><code class="language-ocaml">#require "ppx_let";;
let compute_bounds ~compare list =
  let open Option.Let_syntax in
  let sorted = List.sort ~compare list in
  let%bind first = List.hd sorted in
  let%bind last  = List.last sorted in
  Some (first,last)
;;
&gt;val compute_bounds : compare:('a -&gt; 'a -&gt; int) -&gt; 'a list -&gt; ('a * 'a) option =
&gt;  &lt;fun&gt;
</code></pre>
</div>
<p>Note that we needed a <code>#require</code> statement to enable the extension.</p>
<p>To understand what’s going on here, you need to know that <code>let%bind x = some_expr in some_other_expr</code> is rewritten into <code>some_expr &gt;&gt;= fun x -&gt; some_other_expr</code>.</p>
<p>The advantage of <code>Let_syntax</code> is that it makes monadic bind look more like a regular let-binding. This works nicely because you can think of the monadic bind in this case as a special form of let binding that has some built-in error handling semantics.</p>
</section>
<p>There are other useful idioms encoded in the functions in <code>Option</code>. One example is <code>Option.both</code>, which takes two optional values and produces a new optional pair that is <code>None</code> if either of its arguments are <code>None</code>. Using <code>Option.both</code>, we can make <code>compute_bounds</code> even shorter:</p>
<div class="highlight">
<pre data-filter-output=">" data-prompt="#" class="command-line"><code class="language-ocaml">let compute_bounds ~compare list =
  let sorted = List.sort ~compare list in
  Option.both (List.hd sorted) (List.last sorted)
;;
&gt;val compute_bounds : compare:('a -&gt; 'a -&gt; int) -&gt; 'a list -&gt; ('a * 'a) option =
&gt;  &lt;fun&gt;
</code></pre>
</div>
<p>These error-handling functions are valuable because they let you express your error handling both explicitly and concisely. We’ve only discussed these functions in the context of the <code>Option</code> module, but more functionality of this kind can be found in the <code>Result</code> and <code>Or_error</code> modules.<a data-startref="erraware" data-type="indexterm">&nbsp;</a><a data-startref="EHeraware" data-type="indexterm">&nbsp;</a></p>
</section>
</section>
<section class="level2" id="exceptions">
<h2>Exceptions</h2>
<p>Exceptions in OCaml are not that different from exceptions in many other languages, like Java, C#, and Python. Exceptions are a way to terminate a computation and report an error, while providing a mechanism to catch and handle (and possibly recover from) exceptions that are triggered by subcomputations.<a data-secondary="usefulness of" data-primary="exceptions" data-type="indexterm">&nbsp;</a><a data-secondary="exceptions" data-primary="error handling" data-type="indexterm">&nbsp;</a></p>
<p>You can trigger an exception by, for example, dividing an integer by zero:</p>
<div class="highlight">
<pre data-filter-output=">" data-prompt="#" class="command-line"><code class="language-ocaml">3 / 0;;
&gt;Exception: Division_by_zero.
</code></pre>
</div>
<p>And an exception can terminate a computation even if it happens nested somewhere deep within it:</p>
<div class="highlight">
<pre data-filter-output=">" data-prompt="#" class="command-line"><code class="language-ocaml">List.map ~f:(fun x -&gt; 100 / x) [1;3;0;4];;
&gt;Exception: Division_by_zero.
</code></pre>
</div>
<p>If we put a <code>printf</code> in the middle of the computation, we can see that <code>List.map</code> is interrupted partway through its execution, never getting to the end of the list:</p>
<div class="highlight">
<pre data-filter-output=">" data-prompt="#" class="command-line"><code class="language-ocaml">List.map ~f:(fun x -&gt; Stdio.printf "%d\n%!" x; 100 / x) [1;3;0;4];;
&gt;Exception: Division_by_zero.
&gt;1
&gt;3
&gt;0
</code></pre>
</div>
<p>In addition to built-in exceptions like <code>Divide_by_zero</code>, OCaml lets you define your own:</p>
<div class="highlight">
<pre data-filter-output=">" data-prompt="#" class="command-line"><code class="language-ocaml">exception Key_not_found of string;;
&gt;exception Key_not_found of string
raise (Key_not_found "a");;
&gt;Exception: Key_not_found("a").
</code></pre>
</div>
<p>Exceptions are ordinary values and can be manipulated just like other OCaml values:</p>
<div class="highlight">
<pre data-filter-output=">" data-prompt="#" class="command-line"><code class="language-ocaml">let exceptions = [ Division_by_zero; Key_not_found "b" ];;
&gt;val exceptions : exn list = [Division_by_zero; Key_not_found("b")]
List.filter exceptions  ~f:(function
  | Key_not_found _ -&gt; true
  | _ -&gt; false)
;;
&gt;- : exn list = [Key_not_found("b")]
</code></pre>
</div>
<p>Exceptions are all of the same type, <code>exn</code>. The <code>exn</code> type is something of a special case in the OCaml type system. It is similar to the variant types we encountered in <a data-type="xref" href="variants.html#variants">Chapter 6, Variants</a>, except that it is <em>open</em>, meaning that it’s not fully defined in any one place. In particular, new tags (specifically, new exceptions) can be added to it by different parts of the program. This is in contrast to ordinary variants, which are defined with a closed universe of available tags. One result of this is that you can never have an exhaustive match on an <code>exn</code>, since the full set of possible exceptions is not known.<a data-primary="exn type" data-type="indexterm">&nbsp;</a></p>
<p>The following function uses the <code>Key_not_found</code> exception we defined above to signal an error:</p>
<div class="highlight">
<pre data-filter-output=">" data-prompt="#" class="command-line"><code class="language-ocaml">let rec find_exn alist key = match alist with
  | [] -&gt; raise (Key_not_found key)
  | (key',data) :: tl -&gt; if String.(=) key key' then data else find_exn tl key
;;
&gt;val find_exn : (string * 'a) list -&gt; string -&gt; 'a = &lt;fun&gt;
let alist = [("a",1); ("b",2)];;
&gt;val alist : (string * int) list = [("a", 1); ("b", 2)]
find_exn alist "a";;
&gt;- : int = 1
find_exn alist "c";;
&gt;Exception: Key_not_found("c").
</code></pre>
</div>
<p>Note that we named the function <code>find_exn</code> to warn the user that the function routinely throws exceptions, a convention that is used heavily in Base.<a data-secondary="exception warnings for" data-primary="functions" data-type="indexterm">&nbsp;</a><a data-primary="find_exn function" data-type="indexterm">&nbsp;</a></p>
<p>In the preceding example, <code>raise</code> throws the exception, thus terminating the computation. The type of raise is a bit surprising when you first see it:</p>
<div class="highlight">
<pre data-filter-output=">" data-prompt="#" class="command-line"><code class="language-ocaml">raise;;
&gt;- : exn -&gt; 'a = &lt;fun&gt;
</code></pre>
</div>
<p>The return type of <code>'a</code> makes it look like <code>raise</code> manufactures a value to return that is completely unconstrained in its type. That seems impossible, and it is. Really, <code>raise</code> has a return type of <code>'a</code> because it never returns at all. This behavior isn’t restricted to functions like <code>raise</code> that terminate by throwing exceptions. Here’s another example of a function that doesn’t return a value:</p>
<div class="highlight">
<pre data-filter-output=">" data-prompt="#" class="command-line"><code class="language-ocaml">let rec forever () = forever ();;
&gt;val forever : unit -&gt; 'a = &lt;fun&gt;
</code></pre>
</div>
<p><code>forever</code> doesn’t return a value for a different reason: it’s an infinite loop.</p>
<p>This all matters because it means that the return type of <code>raise</code> can be whatever it needs to be to fit into the context it is called in. Thus, the type system will let us throw an exception anywhere in a program. <a data-primary="sexp declaration" data-type="indexterm">&nbsp;</a><a data-secondary="textual representation of" data-primary="exceptions" data-type="indexterm">&nbsp;</a></p>
<section data-type="note" class="level5 allow_break" id="declaring-exceptions-using-deriving-sexp">
<h5>Declaring Exceptions Using <code>[@@deriving sexp]</code></h5>
<p>OCaml can’t always generate a useful textual representation of an exception. For example:</p>
<div class="highlight">
<pre data-filter-output=">" data-prompt="#" class="command-line"><code class="language-ocaml">type 'a bounds = { lower: 'a; upper: 'a };;
&gt;type 'a bounds = { lower : 'a; upper : 'a; }
exception Crossed_bounds of int bounds;;
&gt;exception Crossed_bounds of int bounds
Crossed_bounds { lower=10; upper=0 };;
&gt;- : exn = Crossed_bounds(_)
</code></pre>
</div>
<p>But if we declare the exception (and the types it depends on) using <code>[@@deriving sexp]</code>, we’ll get something with more information:</p>
<div class="highlight">
<pre data-filter-output=">" data-prompt="#" class="command-line"><code class="language-ocaml">type 'a bounds = { lower: 'a; upper: 'a } [@@deriving sexp];;
&gt;type 'a bounds = { lower : 'a; upper : 'a; }
&gt;val bounds_of_sexp : (Sexp.t -&gt; 'a) -&gt; Sexp.t -&gt; 'a bounds = &lt;fun&gt;
&gt;val sexp_of_bounds : ('a -&gt; Sexp.t) -&gt; 'a bounds -&gt; Sexp.t = &lt;fun&gt;
exception Crossed_bounds of int bounds [@@deriving sexp];;
&gt;exception Crossed_bounds of int bounds
Crossed_bounds { lower=10; upper=0 };;
&gt;- : exn = (//toplevel//.Crossed_bounds ((lower 10) (upper 0)))
</code></pre>
</div>
<p>The period in front of <code>Crossed_bounds</code> is there because the representation generated by <code>[@@deriving sexp]</code> includes the full module path of the module where the exception in question is defined. In this case, the string <code>//toplevel//</code> is used to indicate that this was declared at the utop prompt, rather than in a module.</p>
<p>This is all part of the support for s-expressions provided by the Sexplib library and syntax extension, which is described in more detail in <a data-type="xref" href="data-serialization.html#data-serialization-with-s-expressions">Chapter 19, Data Serialization With S-Expressions</a>.</p>
</section>
<section class="level3" id="helper-functions-for-throwing-exceptions">
<h3>Helper Functions for Throwing Exceptions</h3>
<p>Base provides a number of helper functions to simplify the task of throwing exceptions. The simplest one is <code>failwith</code>, which could be defined as follows: <a data-secondary="helper functions for" data-primary="exceptions" data-type="indexterm">&nbsp;</a><a data-secondary="exception helper functions" data-primary="error handling" data-type="indexterm">&nbsp;</a></p>
<div class="highlight">
<pre data-filter-output=">" data-prompt="#" class="command-line"><code class="language-ocaml">let failwith msg = raise (Failure msg);;
&gt;val failwith : string -&gt; 'a = &lt;fun&gt;
</code></pre>
</div>
<p>There are several other useful functions for raising exceptions, which can be found in the API documentation for the <code>Common</code> and <code>Exn</code> modules in Base.</p>
<p>Another important way of throwing an exception is the <code>assert</code> directive. <code>assert</code> is used for situations where a violation of the condition in question indicates a bug. Consider the following piece of code for zipping together two lists:<a data-primary="assert directive" data-type="indexterm">&nbsp;</a></p>
<div class="highlight">
<pre data-filter-output=">" data-prompt="#" class="command-line"><code class="language-ocaml">let merge_lists xs ys ~f =
  if List.length xs &lt;&gt; List.length ys then None
  else
    let rec loop xs ys =
      match xs,ys with
      | [],[] -&gt; []
      | x::xs, y::ys -&gt; f x y :: loop xs ys
      | _ -&gt; assert false
    in
    Some (loop xs ys)
;;
&gt;val merge_lists : 'a list -&gt; 'b list -&gt; f:('a -&gt; 'b -&gt; 'c) -&gt; 'c list option =
&gt;  &lt;fun&gt;
merge_lists [1;2;3] [-1;1;2] ~f:(+);;
&gt;- : int list option = Some [0; 3; 5]
merge_lists [1;2;3] [-1;1] ~f:(+);;
&gt;- : int list option = None
</code></pre>
</div>
<p>Here we use <code>assert false</code>, which means that the <code>assert</code> is guaranteed to trigger. In general, one can put an arbitrary condition in the assertion.</p>
<p>In this case, the <code>assert</code> can never be triggered because we have a check that makes sure that the lists are of the same length before we call <code>loop</code>. If we change the code so that we drop this test, then we can trigger the <code>assert</code>:</p>
<div class="highlight">
<pre data-filter-output=">" data-prompt="#" class="command-line"><code class="language-ocaml">let merge_lists xs ys ~f =
  let rec loop xs ys =
    match xs,ys with
    | [],[] -&gt; []
    | x::xs, y::ys -&gt; f x y :: loop xs ys
    | _ -&gt; assert false
  in
  loop xs ys
;;
&gt;val merge_lists : 'a list -&gt; 'b list -&gt; f:('a -&gt; 'b -&gt; 'c) -&gt; 'c list = &lt;fun&gt;
merge_lists [1;2;3] [-1] ~f:(+);;
&gt;Exception: "Assert_failure //toplevel//:6:14"
</code></pre>
</div>
<p>This shows what’s special about <code>assert</code>: it captures the line number and character offset of the source location from which the assertion was made.</p>
</section>
<section class="level3" id="exception-handlers">
<h3>Exception Handlers</h3>
<p>So far, we’ve only seen exceptions fully terminate the execution of a computation. But often, we want a program to be able to respond to and recover from an exception. This is achieved through the use of <em>exception handlers</em>.<a data-secondary="exception handlers" data-primary="exceptions" data-type="indexterm">&nbsp;</a><a data-secondary="exception handlers" data-primary="error handling" data-type="indexterm">&nbsp;</a></p>
<p>In OCaml, an exception handler is declared using a <code>try</code>/<code>with</code> statement. Here’s the basic syntax.</p>
<div class="highlight">
<pre><code class="language-clike">try &lt;expr&gt; with
| &lt;pat1&gt; -&gt; &lt;expr1&gt;
| &lt;pat2&gt; -&gt; &lt;expr2&gt;
...</code></pre>
</div>
<p>A <code>try/with</code> clause first evaluates its body, <em><code>expr</code></em>. If no exception is thrown, then the result of evaluating the body is what the entire <code>try/with</code> clause evaluates to.</p>
<p>But if the evaluation of the body throws an exception, then the exception will be fed to the pattern-match statements following the <code>with</code>. If the exception matches a pattern, then we consider the exception caught, and the <code>try/with</code> clause evaluates to the expression on the righthand side of the matching pattern.</p>
<p>Otherwise, the original exception continues up the stack of function calls, to be handled by the next outer exception handler. If the exception is never caught, it terminates the program.</p>
</section>
<section class="level3" id="cleaning-up-in-the-presence-of-exceptions">
<h3>Cleaning Up in the Presence of Exceptions</h3>
<p>One headache with exceptions is that they can terminate your execution at unexpected places, leaving your program in an awkward state. Consider the following function for loading a file full of numerical data. This code parses data that matches a simple comma-separated file format, where each field is a floating point number. In this example we open <code>Stdio</code>, to get access to routines for reading from files. <a data-secondary="exception clean up" data-primary="exceptions" data-type="indexterm">&nbsp;</a><a data-secondary="exception clean up" data-primary="error handling" data-type="indexterm">&nbsp;</a></p>
<div class="highlight">
<pre data-filter-output=">" data-prompt="#" class="command-line"><code class="language-ocaml">open Stdio;;
let parse_line line =
  String.split_on_chars ~on:[','] line
  |&gt; List.map ~f:Float.of_string
;;
&gt;val parse_line : string -&gt; float list = &lt;fun&gt;
let load filename =
  let inc = In_channel.create filename in
  let data = In_channel.input_lines inc |&gt; List.map ~f:parse_line in
  In_channel.close inc;
  data
;;
&gt;val load : string -&gt; float list list = &lt;fun&gt;
</code></pre>
</div>
<p>One problem with this code is that the parsing function can throw an exception if the file in question is malformed. Unfortunately, that means that the <code>In_channel.t</code> that was opened will never be closed, leading to a file-descriptor leak.</p>
<p>We can fix this using Base’s <code>Exn.protect</code> function, which takes two arguments: a thunk <code>f</code>, which is the main body of the computation to be run; and a thunk <code>finally</code>, which is to be called when <code>f</code> exits, whether it exits normally or with an exception. This is similar to the <code>try/finally</code> construct available in many programming languages, but it is implemented in a library, rather than being a built-in primitive. Here’s how it could be used to fix our <code>load</code> function:</p>
<div class="highlight">
<pre data-filter-output=">" data-prompt="#" class="command-line"><code class="language-ocaml">let load filename =
  let inc = In_channel.create filename in
  Exn.protect
    ~f:(fun () -&gt; In_channel.input_lines inc |&gt; List.map ~f:parse_line)
    ~finally:(fun () -&gt; In_channel.close inc)
;;
&gt;val load : string -&gt; float list list = &lt;fun&gt;
</code></pre>
</div>
<p>This is a common enough problem that <code>In_channel</code> has a function called <code>with_file</code> that automates this pattern:</p>
<div class="highlight">
<pre data-filter-output=">" data-prompt="#" class="command-line"><code class="language-ocaml">let load filename =
  In_channel.with_file filename ~f:(fun inc -&gt;
    In_channel.input_lines inc |&gt; List.map ~f:parse_line)
;;
&gt;val load : string -&gt; float list list = &lt;fun&gt;
</code></pre>
</div>
<p><code>In_channel.with_file</code> is built on top of <code>protect</code> so that it can clean up after itself in the presence of exceptions.</p>
</section>
<section class="level3" id="catching-specific-exceptions">
<h3>Catching Specific Exceptions</h3>
<p>OCaml’s exception-handling system allows you to tune your error-recovery logic to the particular error that was thrown. For example, <code>find_exn</code>, which we defined earlier in the chapter, throws <code>Key_not_found</code> when the element in question can’t be found. Let’s look at an example of how you could take advantage of this. In particular, consider the following function: <a data-secondary="catching specific" data-primary="exceptions" data-type="indexterm">&nbsp;</a><a data-secondary="exception detection" data-primary="error handling" data-type="indexterm">&nbsp;</a></p>
<div class="highlight">
<pre data-filter-output=">" data-prompt="#" class="command-line"><code class="language-ocaml">let lookup_weight ~compute_weight alist key =
  try
    let data = find_exn alist key in
    compute_weight data
  with
  Key_not_found _ -&gt; 0.
;;
&gt;val lookup_weight :
&gt;  compute_weight:('a -&gt; float) -&gt; (string * 'a) list -&gt; string -&gt; float =
&gt;  &lt;fun&gt;
</code></pre>
</div>
<p>As you can see from the type, <code>lookup_weight</code> takes an association list, a key for looking up a corresponding value in that list, and a function for computing a floating-point weight from the looked-up value. If no value is found, then a weight of <code>0.</code> should be returned.</p>
<p>The use of exceptions in this code, however, presents some problems. In particular, what happens if <code>compute_weight</code> throws an exception? Ideally, <code>lookup_weight</code> should propagate that exception on, but if the exception happens to be <code>Key_not_found</code>, then that’s not what will happen:</p>
<div class="highlight">
<pre data-filter-output=">" data-prompt="#" class="command-line"><code class="language-ocaml">lookup_weight ~compute_weight:(fun _ -&gt; raise (Key_not_found "foo"))
["a",3; "b",4] "a"
;;
&gt;- : float = 0.
</code></pre>
</div>
<p>This kind of problem is hard to detect in advance because the type system doesn’t tell you what exceptions a given function might throw. For this reason, it’s generally better to avoid relying on the identity of the exception to determine the nature of a failure. A better approach is to narrow the scope of the exception handler, so that when it fires it’s very clear what part of the code failed:</p>
<div class="highlight">
<pre data-filter-output=">" data-prompt="#" class="command-line"><code class="language-ocaml">let lookup_weight ~compute_weight alist key =
  match
    try Some (find_exn alist key)
    with _ -&gt; None
  with
  | None -&gt; 0.
  | Some data -&gt; compute_weight data
;;
&gt;val lookup_weight :
&gt;  compute_weight:('a -&gt; float) -&gt; (string * 'a) list -&gt; string -&gt; float =
&gt;  &lt;fun&gt;
</code></pre>
</div>
<p>This nesting of a <code>try</code> within a <code>match</code> statement is both awkward and involves some unnecessary computation (in particular, the allocation of the option). Happily, OCaml allows for exceptions to be caught by match statements directly, which lets you write this more concisely as follows.</p>
<div class="highlight">
<pre data-filter-output=">" data-prompt="#" class="command-line"><code class="language-ocaml">let lookup_weight ~compute_weight alist key =
  match find_exn alist key with
  | exception _ -&gt; 0.
  | data -&gt; compute_weight data
;;
&gt;val lookup_weight :
&gt;  compute_weight:('a -&gt; float) -&gt; (string * 'a) list -&gt; string -&gt; float =
&gt;  &lt;fun&gt;
</code></pre>
</div>
<p>Note that the <code>exception</code> keyword is used to mark the exception-handling cases.</p>
<p>Best of all is to avoid exceptions entirely, which we could do by using the exception-free function from Base, <code>List.Assoc.find</code>, instead:</p>
<div class="highlight">
<pre data-filter-output=">" data-prompt="#" class="command-line"><code class="language-ocaml">let lookup_weight ~compute_weight alist key =
  match List.Assoc.find ~equal:String.equal alist key with
  | None -&gt; 0.
  | Some data -&gt; compute_weight data
;;
&gt;val lookup_weight :
&gt;  compute_weight:('a -&gt; float) -&gt;
&gt;  (string, 'a) Base.List.Assoc.t -&gt; string -&gt; float = &lt;fun&gt;
</code></pre>
</div>
</section>
<section class="level3" id="backtraces">
<h3>Backtraces</h3>
<p>A big part of the value of exceptions is that they provide useful debugging information in the form of a stack backtrace. Consider the following simple program:<a data-secondary="stack backtraces" data-primary="debugging" data-type="indexterm">&nbsp;</a><a data-primary="stack backtraces" data-type="indexterm">&nbsp;</a><a data-primary="backtraces" data-type="indexterm">&nbsp;</a><a data-secondary="stack backtraces for" data-primary="exceptions" data-type="indexterm">&nbsp;</a><a data-secondary="exception backtracing" data-primary="error handling" data-type="indexterm">&nbsp;</a></p>
<div class="highlight">
<pre><code class="language-ocaml">open Base
open Stdio
exception Empty_list

let list_max = function
  | [] -&gt; raise Empty_list
  | hd :: tl -&gt; List.fold tl ~init:hd ~f:(Int.max)

let () =
  printf "%d\n" (list_max [1;2;3]);
  printf "%d\n" (list_max [])</code></pre>
</div>
<p>If we build and run this program, we’ll get a stack backtrace that will provide some information about where the error occurred and the stack of function calls that were in place at the time of the error:</p>
<div class="highlight">
<pre data-filter-output=">" data-host="lama" data-user="fun" class="command-line"><code class="language-bash">dune exec -- ./blow_up.exe
&gt;3
&gt;Fatal error: exception Dune__exe__Blow_up.Empty_list
&gt;Raised at file "blow_up.ml", line 6, characters 10-26
&gt;Called from file "blow_up.ml", line 11, characters 16-29
[2]</code></pre>
</div>
<p>You can also capture a backtrace within your program by calling <code>Backtrace.Exn.most_recent</code>, which returns the backtrace of the most recently thrown exception. This is useful for reporting detailed information on errors that did not cause your program to fail. <a data-secondary="Backtrace.Exn.most_recent" data-primary="Backtrace module" data-type="indexterm">&nbsp;</a></p>
<p>This works well if you have backtraces enabled, but that isn’t always the case. In fact, by default, OCaml has backtraces turned off, and even if you have them turned on at runtime, you can’t get backtraces unless you have compiled with debugging symbols. Base reverses the default, so if you’re linking in Base, you will have backtraces enabled by default.</p>
<p>Even using Base and compiling with debugging symbols, you can turn backtraces off by setting the <code>OCAMLRUNPARAM</code> environment variable to be empty:</p>
<div class="highlight">
<pre data-filter-output=">" data-host="lama" data-user="fun" class="command-line"><code class="language-bash">OCAMLRUNPARAM= dune exec -- ./blow_up.exe
&gt;3
&gt;Fatal error: exception Dune__exe__Blow_up.Empty_list
&gt;Raised at file "blow_up.ml", line 6, characters 10-26
&gt;Called from file "blow_up.ml", line 11, characters 16-29
[2]</code></pre>
</div>
<p>The resulting error message is considerably less informative. You can also turn backtraces off in your code by calling <code>Backtrace.Exn.set_recording false</code>.<a data-secondary="Backtrace.Exn.set_recording false" data-primary="Exn module" data-type="indexterm">&nbsp;</a></p>
<p>There is a legitimate reasons to run without backtraces: speed. OCaml’s exceptions are fairly fast, but they’re even faster still if you disable backtraces. Here’s a simple benchmark that shows the effect, using the <code>core_bench</code> package:</p>
<div class="highlight">
<pre><code class="language-ocaml">open Core
open Core_bench

exception Exit

let simple_computation () =
  List.range 0 10
  |&gt; List.fold ~init:0 ~f:(fun sum x -&gt; sum + x * x)
  |&gt; ignore

let simple_with_handler () =
  try simple_computation () with Exit -&gt; ()

let end_with_exn () =
  try
    simple_computation ();
    raise Exit
  with Exit -&gt; ()

let end_with_exn_notrace () =
  try
    simple_computation ();
    Exn.raise_without_backtrace Exit
  with Exit -&gt; ()

let () =
  [ Bench.Test.create ~name:"simple computation"
      (fun () -&gt; simple_computation ());
    Bench.Test.create ~name:"simple computation w/handler"
      (fun () -&gt; simple_with_handler ());
    Bench.Test.create ~name:"end with exn"
      (fun () -&gt; end_with_exn ());
    Bench.Test.create ~name:"end with exn notrace"
      (fun () -&gt; end_with_exn_notrace ());
  ]
  |&gt; Bench.make_command
  |&gt; Command.run</code></pre>
</div>
<p>We’re testing three cases here: a simple computation with no exceptions; the same computation with an exception handler but no thrown exceptions; and finally the same computation where we use the exception to do the control flow back to the caller.</p>
<p>If we run this with stacktraces on, the benchmark results look like this:</p>
<div class="highlight">
<pre data-filter-output=">" data-host="lama" data-user="fun" class="command-line"><code class="language-bash">dune exec -- ./exn_cost.exe -ascii cycles -quota 1
&gt;Estimated testing time 4s (4 benchmarks x 1s). Change using -quota SECS.
&gt;
&gt;  Name                           Time/Run   Cycls/Run   mWd/Run   Percentage
&gt; ------------------------------ ---------- ----------- --------- ------------
&gt;  simple computation             177.25ns     353.04c    84.00w       90.04%
&gt;  simple computation w/handler   171.60ns     341.81c    84.00w       87.17%
&gt;  end with exn                   196.85ns     392.11c    84.00w      100.00%
&gt;  end with exn notrace           169.20ns     337.00c    84.00w       85.95%
</code></pre>
</div>
<p>Here, we see that we lose something like 30 cycles to adding an exception handler, and 60 more to actually throwing and catching an exception. If we turn backtraces off, then the results look like this:</p>
<div class="highlight">
<pre data-filter-output=">" data-host="lama" data-user="fun" class="command-line"><code class="language-bash">OCAMLRUNPARAM= ./_build/default/exn_cost.exe -ascii cycles -quota 1
&gt;Estimated testing time 4s (4 benchmarks x 1s). Change using -quota SECS.
&gt;|
&gt;|    Name                           Time/Run   Cycls/Run   mWd/Run   Percentage
&gt;|   ------------------------------ ---------- ----------- --------- ------------
&gt;|    simple computation             428.29ns      1.33kc    84.00w       92.36%
&gt;|    simple computation w/handler   463.72ns      1.44kc    84.00w      100.00%
&gt;|    end with exn                   428.89ns      1.33kc    84.00w       92.49%
&gt;|    end with exn notrace           413.29ns      1.28kc    84.00w       89.13%
</code></pre>
</div>
<p>Here, the handler costs about the same, but the exception itself costs only 25, as opposed to 60 additional cycles. All told, this should only matter if you’re using exceptions routinely as part of your flow control, which is in most cases a stylistic mistake anyway.</p>
</section>
<section class="level3" id="from-exceptions-to-error-aware-types-and-back-again">
<h3>From Exceptions to Error-Aware Types and Back Again</h3>
<p>Both exceptions and error-aware types are necessary parts of programming in OCaml. As such, you often need to move between these two worlds. Happily, Base comes with some useful helper functions to help you do just that. For example, given a piece of code that can throw an exception, you can capture that exception into an option as follows:<a data-secondary="and error-aware types" data-primary="exceptions" data-type="indexterm">&nbsp;</a><a data-primary="error-aware return types" data-type="indexterm">&nbsp;</a><a data-secondary="combining exceptions and error-aware types" data-primary="error handling" data-type="indexterm">&nbsp;</a></p>
<div class="highlight">
<pre data-filter-output=">" data-prompt="#" class="command-line"><code class="language-ocaml">let find alist key =
Option.try_with (fun () -&gt; find_exn alist key)
;;
&gt;val find : (string * 'a) list -&gt; string -&gt; 'a option = &lt;fun&gt;
find ["a",1; "b",2] "c";;
&gt;- : int option = Base.Option.None
find ["a",1; "b",2] "b";;
&gt;- : int option = Base.Option.Some 2
</code></pre>
</div>
<p>And <code>Result</code> and <code>Or_error</code> have similar <code>try_with</code> functions. So, we could write:</p>
<div class="highlight">
<pre data-filter-output=">" data-prompt="#" class="command-line"><code class="language-ocaml">let find alist key =
Or_error.try_with (fun () -&gt; find_exn alist key)
;;
&gt;val find : (string * 'a) list -&gt; string -&gt; 'a Or_error.t = &lt;fun&gt;
find ["a",1; "b",2] "c";;
&gt;- : int Or_error.t = Base__.Result.Error ("Key_not_found(\"c\")")
</code></pre>
</div>
<p>And then we can reraise that exception:</p>
<div class="highlight">
<pre data-filter-output=">" data-prompt="#" class="command-line"><code class="language-ocaml">Or_error.ok_exn (find ["a",1; "b",2] "b");;
&gt;- : int = 2
Or_error.ok_exn (find ["a",1; "b",2] "c");;
&gt;Exception: Key_not_found("c").
</code></pre>
</div>
</section>
</section>
<section class="level2" id="choosing-an-error-handling-strategy">
<h2>Choosing an Error-Handling Strategy</h2>
<p>Given that OCaml supports both exceptions and error-aware return types, how do you choose between them? The key is to think about the trade-off between concision and explicitness.<a data-secondary="strategy choice" data-primary="error handling" data-type="indexterm">&nbsp;</a></p>
<p>Exceptions are more concise because they allow you to defer the job of error handling to some larger scope, and because they don’t clutter up your types. But this concision comes at a cost: exceptions are all too easy to ignore. Error-aware return types, on the other hand, are fully manifest in your type definitions, making the errors that your code might generate explicit and impossible to ignore.<a data-secondary="benefits and drawbacks of" data-primary="exceptions" data-type="indexterm">&nbsp;</a></p>
<p>The right trade-off depends on your application. If you’re writing a rough-and-ready program where getting it done quickly is key and failure is not that expensive, then using exceptions extensively may be the way to go. If, on the other hand, you’re writing production software whose failure is costly, then you should probably lean in the direction of using error-aware return types.</p>
<p>To be clear, it doesn’t make sense to avoid exceptions entirely. The maxim of “use exceptions for exceptional conditions” applies. If an error occurs sufficiently rarely, then throwing an exception is often the right behavior.</p>
<p>Also, for errors that are omnipresent, error-aware return types may be overkill. A good example is out-of-memory errors, which can occur anywhere, and so you’d need to use error-aware return types everywhere to capture those. Having every operation marked as one that might fail is no more explicit than having none of them marked.</p>
<p>In short, for errors that are a foreseeable and ordinary part of the execution of your production code and that are not omnipresent, error-aware return types are typically the right solution.</p>
</section>
</section>
</article></div><a href="imperative-programming.html" class="next-chapter"><div class="content"><h1><small>Next: Chapter 08</small>Imperative Programming</h1></div></a><footer><div class="content"><ul><li><a href="http://twitter.com/realworldocaml">@realworldocaml</a></li><li><a href="http://twitter.com/yminsky">@yminsky</a></li><li><a href="http://twitter.com/avsm">@avsm</a></li><li><a href="https://plus.google.com/111219778721183890368">+hickey</a></li><li><a href="https://github.com/realworldocaml">GitHub</a></li><li><a href="http://www.goodreads.com/book/show/16087552-real-world-ocaml">goodreads</a></li></ul><p>Copyright 2012-2014 Jason Hickey, Anil Madhavapeddy and Yaron Minsky.</p></div></footer><script src="js/jquery.min.js"></script><script src="js/min/app-min.js"></script></body></html>